server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -id: movies-catalog-service
        uri: lb://movies-catalog-service
        predicates:
        -Path=/catalog/**
       routes:
        -id: series-catalog-service
        uri: lb://series-catalog-service
        predicates:
        -Path=/catalog/**
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
