server:
  port : 8097
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://movie-sqldb:3306/movies
    username: root
    password: valen2000
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true

  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq3
    

queue:
  movie:
    name: movieQueue
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
