server:
  port : 8097
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
