server:
  port : 8097
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/examen-final-backend
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
